[application]
name = "mdc-web-test"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "Material Dioxus"

[web.watcher]
index_on_404 = true
watch_path = ["src"]

[web.resource]
style = [
    "https://fonts.googleapis.com/css?family=Roboto:300,400,500",
    "https://fonts.googleapis.com/css?family=Material+Icons&display=block",
]
script = []

[web.resource.dev]
script = []
